In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('coffee_orders.csv')
print("First 10 strings")
display(df.head(10))
print(" \nInto about dataset")
df.info()

First 10 strings

       Напій  Ціна  Кількість   Місто
0        Раф  70.0        2.0   Одеса
1      Латте  60.0        1.0  Дніпро
2  Американо  40.0        1.0    Київ
3  Американо  40.0        NaN  Дніпро
4  Американо  40.0        NaN  Харків
5      Латте  60.0        3.0    Київ
6        NaN   NaN        4.0   Одеса
7   Капучино  55.0        3.0    Київ
8  Американо  40.0        3.0   Одеса
9  Флет Вейт  65.0        1.0  Харків

Into about dataset
<class 'pandas.DataFrame'>
RangeIndex: 1005 entries, 0 to 1004
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Напій      860 non-null    str
 1   Ціна       860 non-null    float64
 2   Кількість  842 non-null    float64
 3   Місто      1005 non-null   str
dtypes: float64(2), str(2)
memory usage: 31.5 KB

In [ ]:
df_clean = df.dropna(subset = ['Напій', 'Ціна']).copy()

df_clean['Кількість'] = df_clean['Кількість'].fillna(1)
df_clean = df_clean.drop_duplicates()
df_clean['Кількість'] = df_clean['Кількість'].astype(int)
print(f"Count lines: {len(df_clean)}")
display(df_clean.head())

Count lines: 120

       Напій  Ціна  Кількість   Місто
0        Раф  70.0          2   Одеса
1      Латте  60.0          1  Дніпро
2  Американо  40.0          1    Київ
3  Американо  40.0          1  Дніпро
4  Американо  40.0          1  Харків

In [6]:
df_clean['Виручка'] = df_clean['Ціна'] * df_clean['Кількість']
print("Statistic")
display(df_clean.describe())

Statistic

             Ціна   Кількість     Виручка
count  120.000000  120.000000  120.000000
mean    53.333333    2.500000  133.333333
std     14.102466    1.122722   71.253286
min     30.000000    1.000000   30.000000
25%     40.000000    1.750000   68.750000
50%     57.500000    2.500000  120.000000
75%     65.000000    3.250000  183.750000
max     70.000000    4.000000  280.000000

In [7]:
heigh_revenue_orders = df_clean[df_clean['Виручка']>150]
print(f'Count big orders: {len(heigh_revenue_orders)}')
display(heigh_revenue_orders.head())
kyiv_orders = df_clean[df_clean['Місто'] == 'Київ'].sort_values(by="Виручка", ascending=False)
display(kyiv_orders.head())

Count big orders: 45

       Напій  Ціна  Кількість   Місто  Виручка
5      Латте  60.0          3    Київ    180.0
7   Капучино  55.0          3    Київ    165.0
13       Раф  70.0          3    Київ    210.0
15  Капучино  55.0          3   Львів    165.0
18     Латте  60.0          3  Дніпро    180.0

         Напій  Ціна  Кількість Місто  Виручка
225        Раф  70.0          4  Київ    280.0
240  Флет Вейт  65.0          4  Київ    260.0
280      Латте  60.0          4  Київ    240.0
56    Капучино  55.0          4  Київ    220.0
13         Раф  70.0          3  Київ    210.0

In [9]:
city_report = df_clean.groupby('Місто').agg(
    Загальна_Виручка = ('Виручка', 'sum'),
    Всього_порцій = ('Кількість', 'mean'),
    Середній_чек = ('Виручка', 'mean')
).reset_index()
city_report = city_report.sort_values(by='Загальна_Виручка', ascending=False)
print("Finance report")
display(city_report)

Finance report

    Місто  Загальна_Виручка  Всього_порцій  Середній_чек
0  Дніпро            3200.0            2.5    133.333333
1    Київ            3200.0            2.5    133.333333
2   Львів            3200.0            2.5    133.333333
3   Одеса            3200.0            2.5    133.333333
4  Харків            3200.0            2.5    133.333333